// 构建并启动本机静态服务后执行 npm run test:web。此检查不替代原生运行验证。
import assert from 'node:assert/strict'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const root = testConfig.root
const { fingerprint } = await import(pathToFileURL(resolve(root, 'scripts/lib/project.mjs')).href)
const task = await taskSpace(testConfig.spaceId || 'Dudu UI 回归验证')
const page = task.page('p1')
const base = testConfig.url || 'http://127.0.0.1:4178'
const route = async (name) => { await page.goto(base + '/#/pages/examples/' + name + '/index'); await page.reload() }
const style = (id) => page.evaluate((id) => { const s = getComputedStyle(document.getElementById(id)); return { background: s.backgroundColor, radius: s.borderRadius, duration: s.transitionDuration } }, id)
mkdirSync(resolve(root, 'reports'), { recursive: true })
await route('button')
await page.waitForSelector('#demo-primary')
const count = () => page.evaluate(() => document.querySelector('#click-count').textContent.trim())
assert.equal(await count(), '有效点击：0')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#demo-primary')).marginBottom), '12px', '组件不能重置宿主纵向间距')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#demo-small')).marginRight), '12px', '组件不能重置宿主横向间距')
await page.evaluate(() => document.querySelector('#demo-primary').scrollIntoView({ block: 'center' }))
const pointer = await page.evaluate(() => { const r = document.querySelector('#demo-primary').getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 } })
await page.cdp('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'left', clickCount: 1, ...pointer })
assert.equal(await page.evaluate(() => document.querySelector('#demo-primary').classList.contains('du-button--pressed')), true)
await page.cdp('Input.dispatchMouseEvent', { type: 'mouseReleased', button: 'left', clickCount: 1, ...pointer })
assert.equal(await page.evaluate(() => document.querySelector('#demo-primary').classList.contains('du-button--pressed')), false)
await page.focus('#demo-primary')
await page.press('#demo-primary', 'Enter')
await page.press('#demo-primary', 'Space')
await page.waitForFunction(() => document.querySelector('#click-count').textContent.trim() === '有效点击：3')
for (const id of ['demo-disabled', 'demo-loading']) {
  assert.equal(await page.evaluate((id) => {
    const el = document.getElementById(id)
    const disabled = el.getAttribute('aria-disabled') === 'true'
    el.dispatchEvent(new MouseEvent('click', { bubbles: true }))
    return disabled
  }, id), true)
  assert.equal(await count(), '有效点击：3')
}
assert.equal((await style('demo-loading')).background, (await style('demo-primary')).background, '加载保持原配色')
assert.equal((await style('demo-loading')).background === (await style('demo-disabled')).background, false, '加载与禁用可区分')
const spinner = await page.evaluate(() => { const s = getComputedStyle(document.querySelector('#demo-loading .du-button__web-spinner')); return { width: s.width, height: s.height, animation: s.animationName, right: s.marginRight, image: s.backgroundImage } })
assert.match(spinner.animation, /^du-button-spin(?:-[a-z0-9]+)?$/)
assert.deepEqual({ ...spinner, animation: 'du-button-spin' }, { width: '16px', height: '16px', animation: 'du-button-spin', right: '0px', image: 'none' })
await page.click('#toggle-loading')
assert.equal(await page.evaluate(() => document.querySelector('#demo-loading').getAttribute('aria-busy')), 'false')
await page.click('#demo-loading')
await page.waitForFunction(() => document.querySelector('#click-count').textContent.trim() === '有效点击：4')
await page.click('#toggle-loading')
assert.equal(await page.evaluate(() => document.querySelector('#demo-loading').getAttribute('aria-busy')), 'true')
await page.click('#demo-secondary')
await page.waitForFunction(() => document.querySelector('#click-count').textContent.trim() === '有效点击：5')
await page.click('#toggle-theme')
assert.equal((await style('demo-primary')).background, 'rgb(144, 180, 255)')
assert.equal((await style('demo-themed')).radius, '12px')
assert.equal(await page.evaluate(() => document.querySelector('#rich-button').tagName), 'BUTTON')
assert.equal(await page.evaluate(() => document.querySelector('#rich-button').textContent.includes('＋') && document.querySelector('#rich-button').textContent.includes('→')), true)
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#circle-button')).width), '48px')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#circle-button')).borderRadius), '24px')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#numeric-button')).height), '64px')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#numeric-button .du-button__text')).fontSize), '21px')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#chromeless-button')).backgroundColor), 'rgba(0, 0, 0, 0)')
assert.equal(await page.evaluate(() => document.querySelector('#slot-button').textContent), '自定义内容')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#unstyled-button')).borderRadius), '0px')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#state-button .du-button__text')).color), 'rgb(255, 255, 255)')
await page.evaluate(() => { const form = document.createElement('form'); form.id = 'button-form'; form.addEventListener('submit', event => { event.preventDefault(); form.dataset.submitted = event.submitter.name + ':' + event.submitter.value }); document.body.append(form) })
await page.click('#form-button')
assert.equal(await page.evaluate(() => document.querySelector('#button-form').dataset.submitted), 'intent:save')
assert.equal(await page.evaluate(() => document.querySelector('#form-button').formMethod), 'post')
await route('input')
await page.waitForSelector('#demo-input input')
assert.equal(await page.evaluate(() => document.querySelector('#demo-input input').getAttribute('aria-label')), '你的称呼')
await page.fill('#demo-input input', 'Dudu')
await page.waitForFunction(() => document.querySelector('#input-value').textContent.includes('Dudu'))
await page.click('#reset-input')
await page.waitForFunction(() => document.querySelector('#demo-input input').value === '')
await page.click('#validate-input')
await page.waitForFunction(() => document.querySelector('#demo-input input').getAttribute('aria-invalid') === 'true')
assert.equal(await page.evaluate(() => document.querySelector('#disabled-input input').disabled), true)
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#demo-input input')).borderRadius), '8px')
await page.fill('#uncontrolled-input input', '内部值')
assert.equal(await page.evaluate(() => document.querySelector('#uncontrolled-input input').value), '内部值')
assert.equal(await page.evaluate(() => document.querySelector('#readonly-input input').readOnly), true)
await page.evaluate(() => { const input = document.querySelector('#readonly-input input'); input.value = '非法修改'; input.dispatchEvent(new Event('input', { bubbles: true })) })
await page.waitForFunction(() => document.querySelector('#readonly-input input').value === '可读内容')
assert.deepEqual(await page.evaluate(() => { const input = document.querySelector('#email-input input'); return { type: input.type, required: input.required, hint: input.enterKeyHint, name: input.name, complete: input.autocomplete, min: input.minLength, pattern: input.pattern } }), { type: 'email', required: true, hint: 'next', name: 'email', complete: 'email', min: 3, pattern: '.+@.+' })
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#email-input input')).height), '56px')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#compact-input input')).height), '44px')
assert.deepEqual(await page.evaluate(() => { const input = document.querySelector('#selection-input input'); return [input.selectionStart, input.selectionEnd] }), [2, 4])
await route('theme')
await page.waitForSelector('#auto-button')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#configured-button')).height), '44px')
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#token-button')).height), '72px')
assert.equal((await style('named-subtheme-button')).background, 'rgb(19, 109, 82)')
assert.equal((await style('inherited-button')).background, 'rgb(19, 109, 82)')
assert.equal((await style('inverse-button')).background, 'rgb(144, 180, 255)')
assert.equal((await style('reset-theme-button')).background, 'rgb(19, 109, 82)')
assert.equal(await page.evaluate(() => document.querySelector('#provider-disabled-button').disabled && document.querySelector('#provider-disabled-input input').disabled), true)
assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#rtl-button .du-button__content')).flexDirection), 'row-reverse')
await page.cdp('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-color-scheme', value: 'dark' }, { name: 'prefers-reduced-motion', value: 'reduce' }] })
await page.waitForFunction(() => getComputedStyle(document.querySelector('#auto-button')).backgroundColor === 'rgb(144, 180, 255)')
assert.equal((await style('light-button')).background, 'rgb(36, 85, 214)')
assert.equal((await style('dark-button')).background, 'rgb(144, 180, 255)')
assert.equal((await style('brand-button')).background, 'rgb(19, 109, 82)')
assert.equal((await style('brand-button')).radius, '12px')
assert.equal((await style('auto-button')).duration, '0s')
assert.equal((await style('auto-inverse-button')).background, 'rgb(36, 85, 214)')
await page.cdp('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-color-scheme', value: 'light' }] })
await page.waitForFunction(() => getComputedStyle(document.querySelector('#auto-button')).backgroundColor === 'rgb(36, 85, 214)')
assert.equal((await style('auto-inverse-button')).background, 'rgb(144, 180, 255)')
for (const width of [375, 1280]) {
  await page.cdp('Emulation.setDeviceMetricsOverride', { width, height: 900, deviceScaleFactor: 1, mobile: width < 500 })
  for (const name of ['button', 'input', 'theme']) {
    await route(name)
    await page.waitForSelector('.lab')
    if (name === 'theme') assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('#responsive-button')).height), width < 768 ? '44px' : '56px')
    if (name !== 'input') assert.equal(await page.evaluate(() => { const buttons = [...document.querySelectorAll('.du-button')]; return buttons.length > 0 && buttons.filter(el => !['circle-button', 'unstyled-button', 'numeric-button'].includes(el.id)).every(el => getComputedStyle(el).borderRadius === '12px') }), true, `${name} 所有按钮圆角一致`)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth && [...document.querySelectorAll('.lab')].every(el => el.getBoundingClientRect().right <= window.innerWidth + 1)), true, `${name} ${width}px`)
  }
  await page.screenshot({ path: resolve(root, `reports/theme-${width}.png`) })
}
const sourceHash = fingerprint()
const reportPath = resolve(root, 'reports/verification.json')
const previous = existsSync(reportPath) ? JSON.parse(readFileSync(reportPath, 'utf8')) : {}
writeFileSync(reportPath, JSON.stringify({ ...previous, 'web-chrome': { status: 'passed', sourceHash, date: new Date().toISOString(), userAgent: await page.evaluate(() => navigator.userAgent), checks: ['easycom', 'click/Enter/Space exactly once', 'disabled/loading event guard', 'loading colors/spinner/exit and re-entry', 'controlled input/reset/error/disabled', 'actual input accessible name', 'externalClasses', 'nested light/dark/auto/brand theme', 'reduced motion', '375px/1280px overflow', 'all button variants/sizes/themes use 12px radius', 'host margins preserved', 'HTML form submitter semantics', 'icons/default slot/circular/numeric/token sizes', 'chromeless/unstyled/forced state', 'uncontrolled/readonly input and HTML input attributes', 'provider defaults/inverse/reset/inherit/rtl/responsive sizes'] } }, null, 2) + '\n')
console.log('通过：按钮、输入、主题、键盘、语义与窄屏回归；证据 reports/verification.json')
if (!testConfig.keep) await task.finish({ keep: [] })
