import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { isMain, root, library, json, components, write } from './lib/project.mjs'

export function themeOutputs(tokens) {
  assert.deepEqual(Object.keys(tokens.themes.light).sort(), Object.keys(tokens.themes.dark).sort(), '亮暗主题变量必须一致')
  const all = { ...tokens.shared, ...tokens.themes.light }
  for (const [name, value] of [...Object.entries(tokens.shared), ...Object.entries(tokens.themes.light), ...Object.entries(tokens.themes.dark)]) {
    assert.match(name, /^[a-z][a-z0-9-]*$/)
    assert.match(value, /^(#[0-9a-fA-F]{6}|[0-9]+(?:\.[0-9]+)?(?:px|ms)|[0-9]+(?:\.[0-9]+)?)$/, `非法 token: ${name}`)
  }
  const vars = (values) => Object.entries(values).map(([name, value]) => `  --du-${name}: ${value};`).join('\n')
  const banner = '// Generated by npm run generate. Edit design-system/tokens.json instead.\n'
  return {
    'tokens.uts': banner + 'export const duSharedTokens: Record<string, string> = ' + JSON.stringify(tokens.shared, null, 2) + '\n' + ['light', 'dark'].map(name => 'export const du' + name[0].toUpperCase() + name.slice(1) + 'Colors: Record<string, string> = ' + JSON.stringify(tokens.themes[name], null, 2)).join('\n') + '\n',
    'tokens.scss': banner + Object.entries(all).map(([name, value]) => `$du-${name}: ${value};`).join('\n') + '\n',
    'theme.scss': banner + `.du-theme--light, .du-theme--auto {\n${vars(all)}\n}\n.du-theme--dark {\n${vars({ ...tokens.shared, ...tokens.themes.dark })}\n}\n@media (prefers-color-scheme: dark) {\n  .du-theme--auto {\n${vars(tokens.themes.dark)}\n  }\n}\n.du-motion--reduced {\n  --du-duration-fast: 0ms;\n  --du-duration-normal: 0ms;\n}\n/* #ifdef WEB */\n@media (prefers-reduced-motion: reduce) {\n  .du-theme--light, .du-theme--dark, .du-theme--auto {\n    --du-duration-fast: 0ms;\n    --du-duration-normal: 0ms;\n  }\n}\n/* #endif */\n`,
  }
}
export function generatedOutputs() {
  const output = new Map()
  for (const [name, content] of Object.entries(themeOutputs(json(resolve(root, 'design-system/tokens.json'))))) {
    output.set(resolve(library, 'styles', name), content)
  }
  const tokens = json(resolve(root, 'design-system/tokens.json'))
  output.set(resolve(root, 'theme.json'), JSON.stringify(Object.fromEntries(Object.entries(tokens.themes).map(([name, colors]) => [name, { navText: name === 'light' ? 'black' : 'white', surface: colors.surface, background: colors.background }])), null, 2) + '\n')
  const entries = components()
  output.set(resolve(library, 'catalog.md'), '# 组件目录\n\n由 npm run generate 生成。experimental 表示 API 尚未冻结，不代表已通过所有平台验证。\n\n| 组件 | 分类 | 状态 | 文档 |\n| --- | --- | --- | --- |\n' + entries.map((entry) => `| ${entry.name} · ${entry.title} | ${entry.category} | ${entry.status} | [API](components/${entry.name}/readme.md) |`).join('\n') + '\n')
  output.set(resolve(root, 'pages/catalog.generated.uts'), '// Generated by npm run generate.\nexport const componentCatalog = ' + JSON.stringify(entries.map(({ name, title, summary, example }) => ({ name, title, summary, path: example })), null, 2) + '\n')
  return output
}
export function generate(check = false) {
  for (const [path, content] of generatedOutputs()) {
    if (check) assert.equal(readFileSync(path, 'utf8'), content, `${path} 已过期：运行 npm run generate`)
    else write(path, content)
  }
}
if (isMain(import.meta.url)) {
  generate(process.argv.includes('--check'))
  console.log(process.argv.includes('--check') ? '生成文件无漂移' : '主题与组件目录已生成')
}
